### ISSUE TITLE
why your repository is that similar proYang outils?

### ISSUE THREAD

**Issue by panzerful** [chenxuan0000/comutils#1]
github.com/proYang/outils
The thief  shout to catch the  thief?      hahahahaha

**Comment by chenxuan0000** [comment]
@panzerful Why use a trumpet to comment instead of zhangkun-Jser ? guilty？ 
https://github.com/zhangkun-Jser/autils   just fork fork form this  and commit  again？

**Comment by panzerful** [comment]
Evil people are samely bad all over the world .
You think you're a good man?
